export const GET_USERS = "GET_USERS";
export const SET_LOADING = "SET_LOADING";
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const REGISTER_USER = 'REGISTER_USER'
export const SIGN_IN_AND_GET_TOKEN = 'SIGN_IN_AND_GET_TOKEN'
export const SET_CURRENT_USER_LOCALLY = 'SET_CURRENT_USER_LOCALLY'